In [18]:
import pandas as pd
import numpy as np

file_path = "../data/interim/CanAI_Cafe_2023_Sales_Information_Step1.csv"

df = pd.read_csv(file_path)

df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Province,Province_cleaned,Item_cleaned,Quantity_imputed_flag
0,TXN_9687814,coffee,2.0,3.5,7.0,Digital Wallet,In-store,2023-09-28,British Columbia,British Columbia,Coffee,0
1,TXN_7002925,Refresher,2.0,5.0,10.0,Cash,NaN,2023-05-02,NL,Newfoundland and Labrador,Refresher,0
2,TXN_7668262,Donut,1.0,2.0,2.0,Digital Wallet,In-store,2023-11-27,British Columbia,British Columbia,Donut,0
3,TXN_8322624,Refresher,3.0,5.0,15.0,ERR_PM_102,In-store,NaN,Saskatchewan,Saskatchewan,Refresher,0
4,TXN_9390285,Coffee,1.0,3.5,3.5,ERR_PM_102,Takeaway,2023-05-11,newfoundland and labrador,Newfoundland and Labrador,Coffee,0

In [19]:
df_cleaned = df.copy()

# Convert blank strings / whitespace-only strings to NaN
df_cleaned = df_cleaned.replace(r'^\s*$', np.nan, regex=True)

# Record row count before cleaning
rows_before = len(df_cleaned)

# Drop Payment Method column
df_cleaned = df_cleaned.drop(columns=['Payment Method'], errors='ignore')

df_cleaned['Transaction Date'] = pd.to_datetime(
    df_cleaned['Transaction Date'],
    errors='coerce'
)

# Identify rows with missing Transaction Date or missing Item
rows_to_drop = (
    df_cleaned['Transaction Date'].isna() |
    df_cleaned['Item'].isna()
)

# Optional: keep a copy of dropped rows for audit/debugging
dropped_rows_missing_date_or_item = df_cleaned.loc[rows_to_drop].copy()

# Drop the rows
df_cleaned = df_cleaned.loc[~rows_to_drop].copy()

# Convert Transaction Date to datetime after dropping missing dates
df_cleaned['Transaction Date'] = pd.to_datetime(
    df_cleaned['Transaction Date'],
    errors='coerce'
)

# Summary
rows_after = len(df_cleaned)
rows_dropped = rows_before - rows_after

print(f"Rows before cleaning: {rows_before}")
print(f"Rows after cleaning: {rows_after}")
print(f"Rows dropped: {rows_dropped}")
print(f"Percentage dropped: {rows_dropped / rows_before * 100:.2f}%")

print("\nRemaining missing values:")
print(df_cleaned.isna().sum().sort_values(ascending=False))

df_cleaned.head()

Rows before cleaning: 10000
Rows after cleaning: 9663
Rows dropped: 337
Percentage dropped: 3.37%

Remaining missing values:
Location                 850
Province                 404
Province_cleaned         404
Quantity                   0
Item                       0
Transaction ID             0
Price Per Unit             0
Transaction Date           0
Total Spent                0
Item_cleaned               0
Quantity_imputed_flag      0
dtype: int64

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Location,Transaction Date,Province,Province_cleaned,Item_cleaned,Quantity_imputed_flag
0,TXN_9687814,coffee,2.0,3.5,7.0,In-store,2023-09-28,British Columbia,British Columbia,Coffee,0
1,TXN_7002925,Refresher,2.0,5.0,10.0,NaN,2023-05-02,NL,Newfoundland and Labrador,Refresher,0
2,TXN_7668262,Donut,1.0,2.0,2.0,In-store,2023-11-27,British Columbia,British Columbia,Donut,0
4,TXN_9390285,Coffee,1.0,3.5,3.5,Takeaway,2023-05-11,newfoundland and labrador,Newfoundland and Labrador,Coffee,0
5,TXN_7321503,Tea,1.0,3.0,3.0,Takeaway,2023-09-15,British Columbia,British Columbia,Tea,0

In [20]:
dropped_rows_missing_date_or_item

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Location,Transaction Date,Province,Province_cleaned,Item_cleaned,Quantity_imputed_flag
3,TXN_8322624,Refresher,3.0,5.0,15.0,In-store,NaT,Saskatchewan,Saskatchewan,Refresher,0
21,TXN_7815208,Cookie,1.0,2.5,2.5,In-store,NaT,Newfoundland,Newfoundland and Labrador,Cookie,0
62,TXN_7857240,Coffee,1.0,3.5,3.5,In-store,NaT,British Columbia,British Columbia,Coffee,0
110,TXN_5176763,NaN,2.0,4.5,9.0,In-store,2023-05-23,Sask.,Saskatchewan,NaN,0
140,TXN_9504987,Cofee,4.0,3.5,14.0,Takeaway,NaT,Newfoundland,Newfoundland and Labrador,Coffee,0
...,...,...,...,...,...,...,...,...,...,...,...
9850,TXN_3386473,Coffee,1.0,3.5,3.5,Takeaway,NaT,British Columbia,British Columbia,Coffee,0
9857,TXN_3318376,Cookie,2.0,2.5,5.0,Takeaway,NaT,Newfoundland,Newfoundland and Labrador,Cookie,0
9868,TXN_7012489,coffee,2.0,3.5,7.0,In-store,NaT,newfoundland and labrador,Newfoundland and Labrador,Coffee,0
9875,TXN_1072343,Cookie,3.0,2.5,7.5,In-store,NaT,Sask.,Saskatchewan,Cookie,0
9910,TXN_3131428,Refresher,4.0,5.0,20.0,In-store,NaT,Newfoundland,Newfoundland and Labrador,Refresher,0

In [21]:
df_cleaned = df_cleaned.drop(columns=['Province', 'Item'], errors='ignore')

print(df_cleaned.columns)

df_cleaned.head()

Index(['Transaction ID', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Location', 'Transaction Date', 'Province_cleaned', 'Item_cleaned',
       'Quantity_imputed_flag'],
      dtype='str')

,Transaction ID,Quantity,Price Per Unit,Total Spent,Location,Transaction Date,Province_cleaned,Item_cleaned,Quantity_imputed_flag
0,TXN_9687814,2.0,3.5,7.0,In-store,2023-09-28,British Columbia,Coffee,0
1,TXN_7002925,2.0,5.0,10.0,NaN,2023-05-02,Newfoundland and Labrador,Refresher,0
2,TXN_7668262,1.0,2.0,2.0,In-store,2023-11-27,British Columbia,Donut,0
4,TXN_9390285,1.0,3.5,3.5,Takeaway,2023-05-11,Newfoundland and Labrador,Coffee,0
5,TXN_7321503,1.0,3.0,3.0,Takeaway,2023-09-15,British Columbia,Tea,0

In [22]:
import numpy as np
import pandas as pd

df_cleaned = df_cleaned.copy()

# Make sure blank strings are treated as missing
df_cleaned = df_cleaned.replace(r'^\s*$', np.nan, regex=True)

rng = np.random.default_rng(seed=42)

def random_sample_from_series(series, rng):
    """
    Randomly sample one value from the observed distribution of a Series.
    """
    observed = series.dropna()

    if observed.empty:
        return np.nan

    probs = observed.value_counts(normalize=True)

    return rng.choice(
        probs.index,
        p=probs.values
    )


def conditional_random_impute(df, target_col, group_col, rng):
    """
    Impute missing values in target_col by randomly sampling from observed values
    within the same group_col category.

    If the group has no observed values, fall back to global random sampling.
    """
    df = df.copy()

    missing_mask = df[target_col].isna()

    for idx in df[missing_mask].index:
        group_value = df.loc[idx, group_col]

        if pd.notna(group_value):
            group_series = df.loc[
                (df[group_col] == group_value) & (df[target_col].notna()),
                target_col
            ]

            sampled_value = random_sample_from_series(group_series, rng)

            if pd.notna(sampled_value):
                df.loc[idx, target_col] = sampled_value
                continue

        # Fallback: sample from overall distribution
        df.loc[idx, target_col] = random_sample_from_series(df[target_col], rng)

    return df


# Add missingness flags before imputing
df_cleaned['Location_missing_flag'] = df_cleaned['Location'].isna().astype(int)
df_cleaned['Province_missing_flag'] = df_cleaned['Province_cleaned'].isna().astype(int)

# Impute Province based on Location
df_cleaned = conditional_random_impute(
    df=df_cleaned,
    target_col='Province_cleaned',
    group_col='Location',
    rng=rng
)

# Impute Location based on Province
df_cleaned = conditional_random_impute(
    df=df_cleaned,
    target_col='Location',
    group_col='Province_cleaned',
    rng=rng
)

# Check result
print("Remaining missing values:")
print(df_cleaned.isna().sum().sort_values(ascending=False))

print("\nLocation missing flag count:")
print(df_cleaned['Location_missing_flag'].sum())

print("\nProvince missing flag count:")
print(df_cleaned['Province_missing_flag'].sum())

print("\nLocation distribution after imputation:")
print(df_cleaned['Location'].value_counts(normalize=True))

print("\nProvince distribution after imputation:")
print(df_cleaned['Province_cleaned'].value_counts(normalize=True))

Remaining missing values:
Transaction ID           0
Quantity                 0
Price Per Unit           0
Total Spent              0
Location                 0
Transaction Date         0
Province_cleaned         0
Item_cleaned             0
Quantity_imputed_flag    0
Location_missing_flag    0
Province_missing_flag    0
dtype: int64

Location missing flag count:
850

Province missing flag count:
404

Location distribution after imputation:
Location
In-store    0.648246
Takeaway    0.351754
Name: proportion, dtype: float64

Province distribution after imputation:
Province_cleaned
British Columbia             0.342854
Newfoundland and Labrador    0.248681
Saskatchewan                 0.206354
Manitoba                     0.200248
Ontario                      0.001863
Name: proportion, dtype: float64

In [24]:
df_cleaned.head()

,Transaction ID,Quantity,Price Per Unit,Total Spent,Location,Transaction Date,Province_cleaned,Item_cleaned,Quantity_imputed_flag,Location_missing_flag,Province_missing_flag
0,TXN_9687814,2.0,3.5,7.0,In-store,2023-09-28,British Columbia,Coffee,0,0,0
1,TXN_7002925,2.0,5.0,10.0,Takeaway,2023-05-02,Newfoundland and Labrador,Refresher,0,1,0
2,TXN_7668262,1.0,2.0,2.0,In-store,2023-11-27,British Columbia,Donut,0,0,0
4,TXN_9390285,1.0,3.5,3.5,Takeaway,2023-05-11,Newfoundland and Labrador,Coffee,0,0,0
5,TXN_7321503,1.0,3.0,3.0,Takeaway,2023-09-15,British Columbia,Tea,0,0,0

In [26]:
df_cleaned = df_cleaned.rename(columns={
    'Province_cleaned': 'Province',
    'Item_cleaned': 'Item'
})

print(df_cleaned.columns)
df_cleaned.head()

Index(['Transaction ID', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Location', 'Transaction Date', 'Province', 'Item',
       'Quantity_imputed_flag', 'Location_missing_flag',
       'Province_missing_flag'],
      dtype='str')

,Transaction ID,Quantity,Price Per Unit,Total Spent,Location,Transaction Date,Province,Item,Quantity_imputed_flag,Location_missing_flag,Province_missing_flag
0,TXN_9687814,2.0,3.5,7.0,In-store,2023-09-28,British Columbia,Coffee,0,0,0
1,TXN_7002925,2.0,5.0,10.0,Takeaway,2023-05-02,Newfoundland and Labrador,Refresher,0,1,0
2,TXN_7668262,1.0,2.0,2.0,In-store,2023-11-27,British Columbia,Donut,0,0,0
4,TXN_9390285,1.0,3.5,3.5,Takeaway,2023-05-11,Newfoundland and Labrador,Coffee,0,0,0
5,TXN_7321503,1.0,3.0,3.0,Takeaway,2023-09-15,British Columbia,Tea,0,0,0

In [28]:
price_check = (
    df_cleaned
    .groupby('Item')['Price Per Unit']
    .agg(
        unique_price_count='nunique',
        unique_prices=lambda x: sorted(x.dropna().unique()),
        row_count='count'
    )
    .reset_index()
    .sort_values(by='unique_price_count', ascending=False)
)

price_check

##Sanity check to see if all the Items have consistent prices. If an Item has more than one unique price, it may indicate data quality issues or variations in pricing.

        Item  unique_price_count unique_prices  row_count
0     Coffee                   1         [3.5]       2707
1     Cookie                   1         [2.5]        933
2      Donut                   1         [2.0]       1089
3      Juice                   1         [4.5]        636
4  Refresher                   1         [5.0]        788
5      Salad                   1         [9.0]        731
6   Sandwich                   1         [8.0]       1253
7        Tea                   1         [3.0]       1526

In [30]:
df_cleaned = df_cleaned.drop(
    columns=['Quantity', 'Price Per Unit', 'Quantity_imputed_flag'],
    errors='ignore'
)

df_cleaned.to_csv("../data/processed/cleaned_transactions.csv", index=False)

print("CSV file created: cleaned_transactions.csv")
print(f"Final dataset shape: {df_cleaned.shape}")

CSV file created: cleaned_transactions.csv
Final dataset shape: (9663, 8)