In [1]:
import pandas as pd
import numpy as np

file_path = "../data/raw/CanAI Cafe 2023 Sales Information.csv"

df = pd.read_csv(file_path)

df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Province
0,TXN_9687814,coffee,2,3.5,7.0,Digital Wallet,In-store,2023-09-28,British Columbia
1,TXN_7002925,Refresher,2,5.0,10.0,Cash,NaN,2023-05-02,NL
2,TXN_7668262,Donut,1,2.0,2.0,Digital Wallet,In-store,2023-11-27,British Columbia
3,TXN_8322624,Refresher,3,5.0,15.0,ERR_PM_102,In-store,NaN,Saskatchewan
4,TXN_9390285,Coffee,1,3.5,3.5,ERR_PM_102,Takeaway,2023-05-11,newfoundland and labrador

In [3]:
rows, columns = df.shape

print(f"Rows: {rows}")
print(f"Columns: {columns}")

Rows: 10000
Columns: 9

In [4]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date', 'Province'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9913 non-null   str
 2   Quantity          9922 non-null   str
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    9568 non-null   str
 6   Location          9285 non-null   str
 7   Transaction Date  9824 non-null   str
 8   Province          9650 non-null   str
dtypes: float64(2), str(7)
memory usage: 703.3 KB

In [6]:
missing_values = df.isnull().sum()
missing_percent = (df.isnull().mean() * 100).round(2)

missing_report = pd.DataFrame({
    "missing_count": missing_values,
    "missing_percent": missing_percent
}).sort_values(by="missing_percent", ascending=False)

missing_report

                  missing_count  missing_percent
Location                    715             7.15
Payment Method              432             4.32
Province                    350             3.50
Transaction Date            176             1.76
Item                         87             0.87
Quantity                     78             0.78
Transaction ID                0             0.00
Total Spent                   0             0.00
Price Per Unit                0             0.00

In [7]:
duplicate_count = df.duplicated().sum()

print(f"Duplicate rows: {duplicate_count}")
print(f"Duplicate percentage: {duplicate_count / len(df) * 100:.2f}%")

Duplicate rows: 0
Duplicate percentage: 0.00%

In [8]:
df["Transaction ID"].duplicated().sum()

np.int64(44)

In [9]:
numeric_columns = df.select_dtypes(include=["int64", "float64"]).columns

df[numeric_columns].describe().T

                  count     mean       std  min  25%  50%   75%   max
Price Per Unit  10000.0  4.34485  2.201565  2.0  3.0  3.5   5.0   9.0
Total Spent     10000.0  8.62880  6.873291  2.0  3.5  7.0  10.5  45.0

In [10]:
categorical_columns = df.select_dtypes(include=["object", "category", "bool"]).columns

for col in categorical_columns:
    print(f"\nColumn: {col}")
    print(df[col].value_counts(dropna=False).head(10))

Column: Transaction ID
Transaction ID
TXN_3000725    2
TXN_3341273    2
TXN_6066756    2
TXN_2817173    2
TXN_3134203    2
TXN_2676077    2
TXN_8355751    2
TXN_7165430    2
TXN_5333530    2
TXN_9655896    2
Name: count, dtype: int64

Column: Item
Item
Coffee       2248
Tea          1257
Sandwich     1060
Cookie        960
Donut         936
Refresher     810
Salad         748
Juice         523
Sandwhich     119
cofee         112
Name: count, dtype: int64

Column: Quantity
Quantity
1      4219
2      2987
3      1587
4       827
5       282
NaN      78
         20
Name: count, dtype: int64

Column: Payment Method
Payment Method
Credit Card       3885
Digital Wallet    3001
Cash              2559
NaN                432
                    95
ERR_PM_102          28
Name: count, dtype: int64

Column: Location
Location
In-store    5915
Takeaway    3207
NaN          715
             163
Name: count, dtype: int64

Column: Transaction Date
Transaction Date
NaN           176
2023-10-09     46
2023-05-25     44
2023-03-02     44
2023-05-26     44
2023-05-17     43
2023-09-06     43
2023-09-28     42
2023-11-10     42
2023-03-09     42
Name: count, dtype: int64

Column: Province
Province
British Columbia             2780
Newfoundland                 1992
Saskatchewan                 1644
Manitoba                     1612
NaN                           350
british columbia              127
New Foundland                 124
BritishColumbia               124
NFLD                          122
newfoundland and labrador     111
Name: count, dtype: int64

C:\Users\ProbanP2\AppData\Local\Temp\ipykernel_2664\233648900.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object", "category", "bool"]).columns

In [11]:
columns_to_check = ["Item", "Payment Method", "Province"]

for col in columns_to_check:
    print(f"\n--- {col} ---")
    print(df[col].dropna().unique())

--- Item ---
<StringArray>
[   'coffee', 'Refresher',     'Donut',    'Coffee',       'Tea',     'Salad',
  'Sandwich',    'Cookie',     'Juice',  'sandwich',      'Tea ', 'Sandwhich',
       'Tee',       'tee',    'cofee ',     'juice',     'Cofee',       'TEA',
  'Doughnut',    'Donutt',    'C0ffee',    'donut ',      'Juic',    'Juicee',
     'coffe',         ' ']
Length: 26, dtype: str

--- Payment Method ---
<StringArray>
['Digital Wallet', 'Cash', 'ERR_PM_102', 'Credit Card', ' ']
Length: 5, dtype: str

--- Province ---
<StringArray>
[         'British Columbia',                        'NL',
              'Saskatchewan', 'newfoundland and labrador',
                  'Manitoba',              'Newfoundland',
                      'B.C.',             'New Foundland',
                        'MB',          'british columbia',
               'Sasktchewan',           'British Columba',
                  'manitoba',                        'SK',
           'BritishColumbia',                      'NFLD',
                     'Sask.',                         ' ',
               'Saskatchewn',          'BRITISH COLUMBIA',
              'saskatchewan',                 'Manitobaa',
                   'Manitba',               'Newfoundlan',
                        'BC',             'Newfoundland ',
           'British Columbi',              'newfoundland',
              'NEWFOUNDLAND',                      'Ont.',
         'British Columbia ',               'Saskatchewa',
                        'ON',             'Saskatchewan ',
                        'mb',                  'MANITOBA',
                   'ontario',                 'Manitoba ',
                  'Ontaroi ',                   'Manitob',
                   'Ontairo',              'SASKATCHEWAN']
Length: 42, dtype: str

In [13]:
columns_to_check = ["Province"]

for col in columns_to_check:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Province ---
Province
British Columbia             2780
Newfoundland                 1992
Saskatchewan                 1644
Manitoba                     1612
NaN                           350
british columbia              127
New Foundland                 124
BritishColumbia               124
NFLD                          122
newfoundland and labrador     111
Manitba                       110
British Columba               107
B.C.                          106
manitoba                       82
Saskatchewn                    81
saskatchewan                   78
Manitobaa                      73
Sasktchewan                    71
Sask.                          71
                               67
SK                             27
BC                             25
MB                             22
NL                             20
BRITISH COLUMBIA                8
British Columbi                 6
Newfoundland                    5
newfoundland                    5
NEWFOUNDLAND                    5
Ont.                            5
British Columbia                5
ON                              5
ontario                         4
Manitoba                        4
Ontaroi                         4
Newfoundlan                     3
Saskatchewa                     3
Saskatchewan                    3
MANITOBA                        3
Manitob                         2
Ontairo                         2
mb                              1
SASKATCHEWAN                    1
Name: count, dtype: int64

In [15]:
columns_to_check = ["Province"]

for col in columns_to_check:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).to_string())

--- Province ---
Province
British Columbia             2780
Newfoundland                 1992
Saskatchewan                 1644
Manitoba                     1612
NaN                           350
british columbia              127
New Foundland                 124
BritishColumbia               124
NFLD                          122
newfoundland and labrador     111
Manitba                       110
British Columba               107
B.C.                          106
manitoba                       82
Saskatchewn                    81
saskatchewan                   78
Manitobaa                      73
Sasktchewan                    71
Sask.                          71
                               67
SK                             27
BC                             25
MB                             22
NL                             20
BRITISH COLUMBIA                8
British Columbi                 6
Newfoundland                    5
newfoundland                    5
NEWFOUNDLAND                    5
Ont.                            5
British Columbia                5
ON                              5
ontario                         4
Manitoba                        4
Ontaroi                         4
Newfoundlan                     3
Saskatchewa                     3
Saskatchewan                    3
MANITOBA                        3
Manitob                         2
Ontairo                         2
mb                              1
SASKATCHEWAN                    1

In [16]:
correlation_matrix = df[numeric_columns].corr()

correlation_matrix

                Price Per Unit  Total Spent
Price Per Unit         1.00000      0.63689
Total Spent            0.63689      1.00000

In [18]:
for col in numeric_columns:
    print(f"\nColumn: {col}")
    print("Min:", df[col].min())
    print("Max:", df[col].max())

Column: Price Per Unit
Min: 2.0
Max: 9.0

Column: Total Spent
Min: 2.0
Max: 45.0

In [21]:
# Convert columns to numeric
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors="coerce")
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors="coerce")

# Only keep rows where Quantity is not missing
df_with_quantity = df[df["Quantity"].notna()].copy()

# Calculate expected total
df_with_quantity["Expected Total Spent"] = (
    df_with_quantity["Quantity"] * df_with_quantity["Price Per Unit"]
)

# Check if Total Spent matches expected total
df_with_quantity["Total Matches"] = np.isclose(
    df_with_quantity["Total Spent"],
    df_with_quantity["Expected Total Spent"],
    atol=0.01
)

# Show rows where Total Spent is incorrect
incorrect_totals = df_with_quantity[df_with_quantity["Total Matches"] == False]

incorrect_totals[
    ["Quantity", "Price Per Unit", "Total Spent", "Expected Total Spent"]
]

Empty DataFrame
Columns: [Quantity, Price Per Unit, Total Spent, Expected Total Spent]
Index: []

In [22]:
for col in numeric_columns:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(f"{col}: {len(outliers)} possible outliers")

Price Per Unit: 754 possible outliers
Total Spent: 621 possible outliers